---
# Install settings necessary to automount USB disks.  FAT32/vfat is
# well supported, need extra packages for NTFS filesystems.

# Automounting is handled by three components, a shell script to mount
# and unmount, a systemd service to manage the mountpoint, and a udef
# rule to trigger on device plug/unplug.

- name: NTFS support installed
  package:
    state: present
    name:
      - ntfs-3g
      
- name: media mount directory present
  file: path="{{ usbdrive_mountdir }}" state=directory
    owner=root group=root mode='0755'

# Get lookup information so that we can mount
# with specific uid=1000,gid=1000,umask=002
- name: Get usbdrive user info
  ansible.builtin.getent:
    database: passwd
  when: usbdrive_user
    
- name: Get usbdrive group info
  ansible.builtin.getent:
    database: group
  when: usbdrive_group

- name: usb-mount script installed
  template: src={{ item }}.j2
    dest=/usr/local/sbin/{{ item }}
    owner=root group=root mode='0755'
  with_items:
    - usb-mount.sh

- name: usb-mount service installed
  copy: src={{ item }}
    dest=/etc/systemd/system/{{ item }}
    owner=root group=root mode='0644'
  with_items:
    - usb-mount@.service
  notify:
    - reload usb-mount service

- name: usb-mount udev rules installed
  copy: src={{ item }}
    dest=/etc/udev/rules.d/{{ item }}
    owner=root group=root mode='0644'
  with_items:
    - 99-local.rules
  notify:
    - reload udev rules
