---
# Defaults for the Jellyfin media server

# Could run as the nas data account if you want jellyfin to have write
# access to the media data or just as its own account if you prefer it
# to have read only access.

# jellyfin_user:     "{{ nas_data_user }}"
# jellyfin_group:    "{{ nas_data_group }}"

jellyfin_user:     jellyfin
jellyfin_group:    jellyfin

jellyfin_cfgdir:   /vault/jellyfin/config
jellyfin_cachedir: /var/cache/jellyfin

jellyfin_volumes:
  - "/data/media:/media"

# - type: bind
#   source: /path/to/media2
#   target: /media2
#   read_only: true
