---
# Defaults for the Jellyfin media server
jellyfin_user:     "{{ nas_data_user }}"
jellyfin_group:    "{{ nas_data_group }}"

jellyfin_cfgdir:   /vault/jellyfin/config
jellyfin_cachedir: /var/cache/jellyfin

jellyfin_volumes:
  - "/data/media:/media"

# - type: bind
#   source: /path/to/media2
#   target: /media2
#   read_only: true
