---
# Defaults for the Jellyfin media server

# Could run as the nas data account if you want jellyfin to have write
# access to the media data or just as its own account if you prefer it
# to have read only access.

# jellyfin_user:     "{{ nas_data_user }}"
# jellyfin_group:    "{{ nas_data_group }}"

jellyfin_user:     jellyfin
jellyfin_group:    jellyfin

jellyfin_cfgdir:   /var/lib/jellyfin
jellyfin_cachedir: /var/cache/jellyfin

jellyfin_volumes:
  - "/data/media:/media"

# - type: bind
#   source: /path/to/media2
#   target: /media2
#   read_only: true

jellyfin_hwa_groups: []
jellyfin_hwa_devices: []
jellyfin_hwa_custom:

# Appropriate settings for Intel 
jellyfin_hwa_groups_intel:
  - video
  - render
  
jellyfin_hwa_devices_intel:
  - "/dev/dri:/dev/dri"
  
# Not tested with NVIDIA, but docs say you need the
# following in the config.  Set jellyfin_hwa_custom
# to a string containing something like the following
#
#     runtime: nvidia
#     deploy:
#       resources:
#         reservations:
#           devices:
#             - driver: nvidia
#               count: all
#               capabilities: [gpu]  
