---
# CLOUD MACHINE WITH MAIL AND WEB

#==============================
# Network and Firewall - Appropriate ports will be opened for named
# services (mail=submission and imaps, apache=http/https, etc).  SSH
# is always open.  Any extra ports go in the lists below.  Fail2ban
# also checks the services list to see what jails to use.
#
firewall_services: [ 'mail', 'web' ]
#firewall_opentcp: [any extra ports]
#firewall_openudp: [any extra ports]

# fail2ban ignores these networks.  If running a webmail machine, add
# its address here, as it does its own banning upstream, and you don't
# want the entire webmail machine banned from dovecot because a third
# party machine is banging on the login page.
# fail2ban_ignoreips: []

# If you want daily logwatch reports
# use_logwatch: yes

#==============================
# Encrypted Directories - Override the directories for various
# packages to keep the data in an encrypted partition at rest.
#
cryptdir_root: /vault

# Default is gocryptfs, use LUKS if we have a separate partition
#cryptdir_type: luks
#cryptdir_luks_dev: "/dev/replace-with-real-device"

# mailboot script generated by the cryptdir role
cryptdir_boot_script: /usr/sbin/mailboot
cryptdir_boot_services:
  - postfix
  - dovecot
  - redis-server
  - rspamd

# start services at boot unless using encrypted dirs
mail_services_bootstart: "{{ cryptdir_type == 'none' }}"

# Keep mail spool, user database and keys in the encrypted directory.
# You can move the mail queue there if using luks, but not with encfs.
mail_spool_root:        "{{cryptdir_root}}/vmail"
mail_db_root:           "{{cryptdir_root}}/maildb"
mail_sieve_root:        "{{cryptdir_root}}/sieve"
mail_dkim_root:         "{{cryptdir_root}}/dkim"
redis_dbdir:            "{{cryptdir_root}}/redis"
# only if using luks
#mail_queue_dir:        "{{cryptdir_root}}/postfix"

# fcntl does not work with encfs, use dot locking instead
dovecot_use_dotlock: "{{ cryptdir_type|default('encfs') == 'encfs' }}"

# Web data usually left in the default /var/www, but you can move it
# under the encrypted root if you want to.  Add apache to the mailboot
# services above if you do.
#
webdata_root:           /var/www
#webdata_root:          "{{cryptdir_root}}/www"

# stop/start these during the challenge response period
certbot_service_stop:
  - apache2

# also reload these when we get a new cert.
certbot_service_reload:
  - postfix
  - dovecot

#==============================
# Backup Directories - for mail and web server
# WHEN LIST CHANGES, REBUILD BACKUP SERVER, NOT CLIENT
#
# Should we include the rspamd dbdir /var/lib/rspamd
#
bacula_client_fileset:
  include:
    - /etc/letsencrypt
    - /var/log
    - "{{mail_db_root}}"
    - "{{mail_dkim_root}}"
    - "{{mail_sieve_root}}"
    - "{{mail_spool_root}}"
    - "{{redis_dbdir|default('/var/lib/redis', true)}}"
    - "{{webdata_root}}"
