---
# NAS/BACKUP SERVER MACHINE

# use_logwatch: yes
# use_autofs: yes

firewall_services: [ 'samba' ]
#firewall_services: [ 'web', 'samba', 'jellyfin', 'plex' ]


# ZFS Filesystems
#
# Use the disk ID from /dev/disk/by-id when creating the pool because
# it is more stable than sda/sdb if disks are moved around.
#
# Use entire SSD as cache for the pool.  If we ever add a second pool,
# we can remove the SSD as cache, partition it into two, and then add
# one partition back to each pool.
#
# The default settings enable case sensitive filesystem, utf8
# filenames and formD comparison (for Mac compatibility).  Those need
# to be specified at create time.  Can add quotas later if desired to
# limit filesystem sizes.
#      quota: 200G
#
zfs_pools: 
  - name: tank
    vdev: >-
       mirror 
       ata-BIGDRIVE1
       ata-BIGDRIVE2
       cache
       nvme-FASTDRIVE

zfs_filesystems:
  # Common data for music, pictures, and movies
  - name: tank/public
    properties:
      mountpoint: /public
      casesensitivity: mixed

  # System data for like bacula backups of mail server
  - name: tank/vault
    properties:
      mountpoint: /vault
       
  # Individual personal files
  # samba users homedirs on ZFS, sys accts still /home
  - name: tank/home
    properties:
      mountpoint: "{{ nas_home }}"

# ZFS Snapshots -- keep snapshots, but dial back the frequency a bit.
# Do not snapshot the Bacula backups, since they already carry a full
# history.
zfs_snapshot_policy:
  tank/home:   { use_template: base }
  tank/public: { use_template: base }
  tank/vault:  { use_template: none }
        
zfs_snapshot_templates:
  # for the bacula backups
  none:
    autosnap: no
    
  # use default frequency and retention
  base:
    autosnap: yes
    autoprune: yes

# Monitor smart status on these drives
smartd_drives:
  - /dev/disk/by-id/ata-BIGDRIVE1
  - /dev/disk/by-id/ata-BIGDRIVE2
  # boot drive
  - /dev/disk/by-id/nvme-BOOTDRIVE
  # zfs cache drive
  - /dev/disk/by-id/nvme-FASTDRIVE


# Allow hard drives to spin down in 20min
hdparm_drives:
  /dev/disk/by-id/ata-BIGDRIVE1
    apm: 127
    spindown_time: 240
  /dev/disk/by-id/ata-BIGDRIVE2
    apm: 127
    spindown_time: 240


samba_shares:
  - name: homes
    comment: Home Directories
    browseable: false

    # By default, the home directories are exported read-only. Change the
    # next parameter to 'no' if you want to be able to write to them.
    read only: true

    # File creation mask is set to 0700 for security reasons. If you want to
    # create files with group=rw permissions, set next parameter to 0775.
    create mask: '0700'

    # Directory creation mask is set to 0700 for security reasons. If you want to
    # create dirs. with group=rw permissions, set next parameter to 0775.
    directory mask: '0700'

    # By default, \\server\username shares can be connected to by anyone
    # with access to the samba server.
    # The following parameter makes sure that only "username" can connect
    # to \\server\username
    # This might need tweaking when using external authentication schemes
    valid users: '%S'

  - name: data
    comment: Data Share
    path: /public
    browseable: true
    writable: true
    create mask: '0755'
    directory mask: '0775'
    force user:  "{{ nas_data_user }}"
    force group: "{{ nas_data_group }}"
    
# read only = !writable
# allow delete readonly?  Lets user delete file if readonly like on unix but not dos.
# fake directory create times if doing nmake builds on the share
# force user = nas-data to make all files owned by nas-data

# invalid users = root deploy admin @wheel 

# make everything on here owned by nas-data for simplicity
nas_data_shares:
  - /public


# NAS users
# Set smbonly if the unix account exists already from some other
# action and you just want to set the smb password.  The account must
# already exist at this point if you set to true.

nas_users:
  - name: someuser
    pw: "{{ vault_nas_someuser_pw }}"
    # home: /homenas/someuser   if want homedir elsewhere
    # smbonly: true             skip create unix acct


# We install the bacula client on the director machine too, because we
# need to back up our own file catalog, but we do not need the tunnel.
bacula_client_tunnel: no


    
