---
# Defaults, properties are only set at pool or filesystem creation
# https://openzfs.github.io/openzfs-docs/man/7/zfsprops.7.html
# https://openzfs.github.io/openzfs-docs/man/7/zpoolprops.7.html

# Normalize arch reported by Ansible to the Debian usage.  The header
# packages are linux-headers-amd64 or linux-headers-arm64.  Check your
# setup if using a different architecture.
zfs_debian_arch: "{{ {
        'x86_64': 'amd64',
        'aarch64': 'arm64'
        } [ansible_architecture] |
        default(ansible_architecture) }}"
zfs_kernel_headers: "linux-headers-{{ zfs_debian_arch }}"


# Use the disk ID from /dev/disk/by-id when creating the pool because
# it is more stable than sda/sdb if disks are moved around.
#
zfs_pools: []
#   - name: mypool
#     vdev: >-
#       mirror
#         dev1
#         dev1
#       mirror
#         dev1
#         dev2
#       log dd
#     dont_enable_features: false
#     properties:
#       ashift: 9
#     filesystem_properties:
#     extra_import_options: ""
#     extra_create_options: ""
# https://openzfs.github.io/openzfs-docs/man/7/zpoolprops.7.html
zfs_pools_defaults: {}

zfs_pools_force_import: true


zfs_filesystems: []
#   - name: mypool/myfs
#     properties:
#        mountpoint: /myfs
#        casesensitivity: mixed
# 


# Casesensitivity, encryption, keyformat, pbkdf2iters, utf8only, and
# normalization can only be set at creation time.  formD normalization
# is the recommended value for interoperation with MacOS.
# 
# Can add quotas later if desired to limit filesystem sizes.  Note
# that you can use M/G/T units for the quota, but you may want to
# convert it to bytes yourself.  When using M/G/T, Ansible shows the
# value as changed because zfs reports current the quota in bytes.
#    quota: 200G

zfs_filesystems_properties_defaults:
  acltype: posix
  atime: false
  canmount: true
  casesensitivity: sensitive
  compression: lz4
  dedup: false
  normalization: formD
  setuid: true
  snapdir: hidden
  sync: standard
  utf8only: true
  
  # As of OpenZFS 2.3.0 xattr=on is equivalent to xattr=sa on Linux
  # Older versions should still use sa.
  xattr: on


#========================================
# ZFS Snapshot Policy with SANOID.  If policy is set, install sanoid
# and create sanoid.conf with the hash of parameters associated with
# each drive.

use_sanoid:
  "{{ (zfs_snapshot_policy|length) > 0 }}"

  
# Policy for individual filesystems.  Typically just set use_template
# to apply templates defined by zfs_snapshot_templates.  Local
# overrides can be added as needed however.
#
# zfs_snapshot_policy:
#    zpoolname/datasetname:
#       use_template: base
#
#       # local overrides
#       hourly: 12
#       monthly: 1
#
zfs_snapshot_policy: {}

# Common templates, numbers indicate how many copies to keep before
# pruning.  For example daily: 7 is keep seven daily snapshots.
#
zfs_snapshot_templates:
  base:
    frequently: 0
    hourly: 24
    daily: 7
    weekly: 4
    monthly: 6
    yearly: 0
    autosnap: yes
    autoprune: yes


# Sanoid runs periodically from a systemd timer.  If the default timer
# is not appropriate, change here.  May be needed if it prevents disks
# from going into standby.
#
# zfs_snapshot_timer:
#    OnCalendar: daily
#    Description: Run Sanoid Daily
#
zfs_snapshot_timer: {}
    
