---

#========================================
# USB Drive Mount Flags
#

# Drives will be automounted by label under here
usbdrive_mountdir: /media

# change to async for faster performance, but must umount before
# removing it.
usbdrive_sync: sync

# Mount vfat/ntfs as the following if desired
usbdrive_user:
usbdrive_group: 
usbdrive_umask: '002'

