---
# PRIVATE VAULT FILE
# ENCRYPT THIS FILE BEFORE MAKING ANY CHANGES!
# ENCRYPT THIS FILE BEFORE MAKING ANY CHANGES!
# ENCRYPT THIS FILE BEFORE MAKING ANY CHANGES!
#
# ansible-vault encrypt vault.yml	# encrypt plain file
# ansible-vault edit vault.yml 		# run EDITOR on encrypted file
# ansible-vault rekey vault.yml 	# change password on file
#
# This holds sensitive information like passwords and accounts.  This
# file can stay encrypted while less sensitive settings are cleartext
# in the all.yml file.  Everything can be kept under source control.

# Generate modern SSH keys for deploy and the bacula tunnel:
#
# ssh-keygen -t ed25519 -f deploy -C deploy-yourhost -N ''
# ssh-keygen -t ed25519 -f bacula -C bacula-tunnel-yourhost -N ''
# ssh-keygen -t ed25519 -f www -C www-yourhost -N ''
#
# Create the pwhash for passwords with "mkpasswd --method=sha-512"
#
vault_deploy_sshpub: ~/.ssh/id_deploy.pub
vault_deploy_sshkey: ~/.ssh/id_deploy
vault_deploy_pwhash: [change me to hash like $6$verylongcryptstring]

# Separate account without any sudo access for uploading web content.
vault_www_sshpub: ~/.ssh/id_www.pub
vault_www_sshkey: ~/.ssh/id_www

# Bacula passwords coordinate between director and the daemons.  You
# can just make these 50-60 char long strings of gibberish.
vault_bacula_tunnel_sshpub: ~/.ssh/id_bacula.pub
vault_bacula_tunnel_sshkey: ~/.ssh/id_bacula
vault_bacula_client_pw:  [change me to very long gibberish]
vault_bacula_storage_pw: [change me to very long gibberish]
vault_bacula_console_pw: [change me to very long gibberish]
#vault_bacula_db_pw: [if using pgsql or mysql]

# The cryptdir password is for mounting the encrypted directory that
# contains the mail spool.  The relay password is for client machines
# to authenticate to the mailhost so they can send local system mail.
vault_cryptdir_pw: [change me to cleartext password]
vault_relay_pw:    [change me to cleartext password]

# Mailbox passwords.  Add as needed for your users.  These can be
# changed later with the mailcfg tool.  You might want to move the
# entire mail_users var here to keep the email addresses private.
vault_mbox_admin_pw: [change me to cleartext password]
vault_mbox_user1_pw: [change me to cleartext password]
vault_mbox_user2_pw: [change me to cleartext password]
vault_mbox_user3_pw: [change me to cleartext password]


# Session data encryption. For DES must be 24char, but we use AES
vault_webmail_des_key: '123456789012345678901234'

